apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
spec:
  description: Shared observability stack

  sourceRepos:
    - "*"

  destinations:
    - namespace: "observability"
      server: "https://kubernetes.default.svc"
    - namespace: "kube-system"
      server: "https://kubernetes.default.svc"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
