apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
spec:
  description: Shared observability stack

  sourceRepos:
    - '*'

  destinations:
    - namespace: 'observability'
      server: 'https://kubernetes.default.svc'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
