apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform infrastructure services

  sourceRepos:
    - 'https://github.com/Black-And-White-Club/all-infrastructure.git'
    - 'https://github.com/Black-And-White-Club/all-infrastructure'
    - 'https://argoproj.github.io/argo-helm'
    - 'https://bitnami-labs.github.io/sealed-secrets'
    - 'https://charts.jetstack.io'
    - 'https://kubernetes.github.io/ingress-nginx'

  destinations:
    - namespace: 'argocd'
      server: 'https://kubernetes.default.svc'
    - namespace: 'cert-manager'
      server: 'https://kubernetes.default.svc'
    - namespace: 'ingress-nginx'
      server: 'https://kubernetes.default.svc'
    - namespace: 'kube-system'
      server: 'https://kubernetes.default.svc'
    - namespace: 'default'
      server: 'https://kubernetes.default.svc'
    - namespace: ''
      server: 'https://kubernetes.default.svc'

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: Node
    - group: ''
      kind: PersistentVolume
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'storage.k8s.io'
      kind: StorageClass
    - group: 'storage.k8s.io'
      kind: CSIDriver
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingWebhookConfiguration
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
    - group: 'apiregistration.k8s.io'
      kind: APIService
    - group: 'networking.k8s.io'
      kind: IngressClass
    - group: 'scheduling.k8s.io'
      kind: PriorityClass
    - group: 'cert-manager.io'
      kind: ClusterIssuer
    - group: 'argoproj.io'
      kind: AppProject

  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: Endpoints
    - group: ''
      kind: Pod
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: DaemonSet
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: ReplicaSet
    - group: 'batch'
      kind: Job
    - group: 'batch'
      kind: CronJob
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
    - group: 'rbac.authorization.k8s.io'
      kind: Role
    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding
    - group: 'policy'
      kind: PodDisruptionBudget
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'coordination.k8s.io'
      kind: Lease
    - group: 'cert-manager.io'
      kind: Certificate
    - group: 'cert-manager.io'
      kind: Issuer
    - group: 'bitnami.com'
      kind: SealedSecret
    - group: 'argoproj.io'
      kind: Application
    - group: 'argoproj.io'
      kind: AppProject
    - group: 'argocd-image-updater.argoproj.io'
      kind: ImageUpdater
