---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAWIQp83W4Q8Q28KfSEwVZ/+9QZMZeTL9A/wU4lAivXthcXrqe5U8A4CIpbdGn2mLMtYI+EcbjXjLd6EOYR81F3NwZ4Om1e2WX/6qeQ4SQTUMiyhoRuusvbGU0LFqvvO9BCw0tod9eWjFsxGKxMNEBHtRH82KpaxV6UXQtF8sjqNzewUN7umg/HdxlWo+jJ8UT7wrZbPgX28cPoskPcyjaCXiI8fgMg9q6fknm1XGdSFGOjXfuhqQwNC5q7TIu+nuNQSC9QVhGuONARsbs9/MnJazpAZlXHbc+c2pO+4IMOo7cfqwnMa5PNGWAYyQs+ToUj9PdDykJiWiyxTI0iljmMT8xm9C+8hHsoln+CNw4Ug9c7St7ZWVcLVhW0PaUaKAcSdA5NDh1P5LuvatObqbwXwEB6roM6agxHMkZxB/6lioc/wjvryuGKc50iRYrxQ5mN1VzgU1mFngbTO98vkOEYe7HTL9lPUzEb1Q/Cd8EjlNfvcYDMcvSzaotU6SmNBQm8e3Q0acnj8dt6MJqTdzo+JFYZVPfppRCufSj/1sibbo89VqMZInPQlCO78hI3+v+OHI+4a1DIrpEzfCKPgNly5V0NcQ9Cnmv/2rbWa7b0LInF9+e+nme3gTetoTY9kSjVL1tZGypCtluI+g90zJnJX2v5R/sXARpht/+NkYRL36r7BdClymzRzHszUA5p7P+GK53MFnEj+VUfRhj5rp1ZihyZTL59DgjY4ZZ1H2WRVJmBpbxwWilY6M/ZKA==
    admin-user: AgCS4q4gJvBZiqt+Jgqh3vMaMQUiyGIcH1dhNMsPeqMOVUjloF6jzZ6F+rcEF57rXahk/E1SKCEneKYf0eBIKbGmKKEk4KG8+x4VgpQqBSvCZbj5T+/amm+JGuJ+PD5l41pwDqd3NIsjmWeo91E4QJbY9edMliobJObkknmoiVVqRTRKOUqPjOxxsba0hU8ssFMk8zpweVQ3nqCnTSF/fAR6zMXl80hBfBlk2Qi2pLADBoqzUKvWzMDSTbXdslbrcZHYrv68Fkw/+9A0YYfRpC87tWJO4GQ3D8pXWxOlGUuq7PqNCQ/KippXNdiVu0jZeBn/l2fS+0oWTXX0z5ioWLzDwFd1DkyRMmNd+WwTt7+OXZSXIh92UxmJ3cE5bz1iOvh+z9Hu45JUrqG939f0SZdpWJDT9rilPd4fN+lMKs7poSC1ai/jTe2FsON9uDTgslKsBW5BPe5dEcCw6/otppgSo37uaZUpLmT1H/0skXJteCKQXchYUpsHz6Z7brw6detvQ0JHfobn/tZLDzKL5qr9UslYWv7bdRutPTfM86CAma8GjpYZ4WwwyYyFfRBhi7cpwjqRxuLlzhPE3F+u+BOkiYeMHrvHg+X3fZSC/oemYDHjrw9wwfXPhV6blBCsguocl5oJUCiBlojMTGWSMOJMpRChf1kadwZGFwDDeOmwGNK1Re84x4ddSU4mUovJWTMir0uxnw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: observability
