---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocir-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgA3mDmPJTpZH2bR+EVMWQJLjrBkTQJ24RI4SgUVV935FIAmuZK5QaBZ/3MIuAzjqCBfulwt1lIB0pxOOMEPYWAjZqk5TTsa7Rf84421dp0nIHbglZb73sGv2mIpYwpQgEmG402bkBCOP8hKmfbD6hAtsepFzayy/UTf007WF2lP7tnekiSquAvpepsQQnhnKdKc7kmbQiIIDgROLwYB/k5ftTjgREgOPayypzV3KJ0KtcWjLO1pUJWuN1E2fBgxySMAhPOODnP9hHyNTjMFEoBeagvUf2OI7QS/hYMlVrPHHG7BKuW/QykJ385J2GYq/wSwYzfQbQaJ/HhcSF97+P9TmlddA+dNySlCBOLzAMZUoOF2u8WGCUOAoBN6WUyJfVNpG/uQaS21rB9L362ljS+h+jUpFZ6Pm7JldwP3zWV6R8rRqLsvufNtydOrq0RQgGwZe2zCLlmfhPt0Gcf6EkqGMG4Of2X5gH1zYGlXp3DXi581atDyzt+Y3120QlBIkBFdlVubuIidlI5NYZohQ3wKcs4WwTY99sO1vwQyuxFN2tdWX7O3qHOUZwVgzcEFCyZ2GRzpjOh46/xJ9YanQ3G+iP+WJXL3fLCYJ87kl2snXlT8reGioM4T6ET8c2sHh+zh0vVH0dNccQyz2Pc+IVKDNF3xZ9lIaVwR3dYTvLkMX3151ng39yiCi2itKAXBaa+Oyiq2cewSPi6mmLLIzjNbtK7827Qlu8c+veVPnapCbZDLH1l3sazSszbqNcwtgbMH5tOocEmwMBvBm8sziRCWG95lwk+TQNn/JWN5qzrW9eBV+mCiWK3ne/yXA5Bb9Z7yygrSsJwOOP/izwzbRUNL2eRZnV8fGW5Onax30nHPMbKlkXSwzaE190JIzv0H7oWevzwqZVWJpCT6IPiH4IMuyC4NbD9Dr2tckyQo4x0zlfWD+p3t0V/JlUV5X5VUQuhojEtjtdNDPBKaDRSM/iqWqnIuM/lClHJTYHCI2EJIbvH5RoomYasTe0RvGA==
  template:
    metadata:
      name: ocir-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
