---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocir-secret
  namespace: resume-app
spec:
  encryptedData:
    .dockerconfigjson: AgAGdD+eBwGMZ+HVnL3Qi4Ae8bEHgoJIf/tSAzFzl/7TechyIeiM2Nswc+yl3EaBGfQiaUPukVkBBKgbeSOH/KohO3F+veogIPIMEb0oB54WiaL4qjCgP1fufFqK2qjjxeh8e1kFj+DupA49zPdEbKW4Xw0erwzuMgdTsH1l9HsxURo0k6Jd9AorUkh9y5EmrUQPOmkh+GeI8g8vvDSxKSO9jEMVNf0hRv0ChiqH8kLiFBML/zXPKRUjcxWbL0COMw9emnJv0GNueq/3GKP9YqQi011qakbGSOeJI5joU/dPGEiKZBl+qETZXduEs4MV81OdzJxp1O1hB++unRYKhPWcy6xcgBQMDvyizBj6pvSpq3sMb1YgYsOhV23l8Qt0sCzQQV3LPiy5eC+H+KqY/9K4mH21tblCXjSPg7FX0FFYmFYR5dWnmR0HDFymDJ153W0kIBG3dExxNFGoL1/lfzRei0dYer8autR+sJinaQE9GerKFn+pv1+r1eesBQCER2vgjz/pkZXVNTKjHuXgwyHUBqRaiYhZWY4fIBhTWX0E3173u6bc5ETZTUPNUkCFgGC8BF3/tjdhwbdfTad6I3Co6C3w/bQfFl3wI29KWwgJFBOd3wPyHpVhE8xsuknaOnz45yrfGo5IgEJPH38vR5zrxq9mydrLLB+OQVoMIYpjTiiMVFgyngXkgVKr+XrRl5Hm27yNCtpIRVRcSrH1SGWDXCNd1NjaCd4WHCq1CsqDzcn14wIA5jA0isRLaF0tThc2xW6tNgzk1l+xl2HG4qyTudkkdSaco9IaDXJ6USEpR1ZSxf0hPtUWCg0fGa9ZW0GJ7brgIktmh4+Q09UgxV5OSsV7Sg9vnAbJdcgll7RSoiqg1ucDHNO0op05T1vae36PVkDTsCih0ukN4IhZy6eM01AQGEy7iSsJQVW2bONEY8g93sgkSVdBPJnrxvj1fV1Dc+wy9KtH
  template:
    metadata:
      name: ocir-secret
      namespace: resume-app
    type: kubernetes.io/dockerconfigjson
