---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocir-secret
  namespace: resume-app
spec:
  encryptedData:
    .dockerconfigjson: AgBtbQR7NDw9ueY37zJ4WvaVEX6uezN0beAkVSm2qzJY7kjmI1bTHgFalybWJ1ZWuicsAj0OXSYJXFFLlpoVsOyMa1gWRPWgOaUaoTarL66ZpeXNPNidVN8EKOTCV1fjzMAnTlB3VcJxNnzjXYclFC0Jsj1FUeTd7cPDyf8+9xGuyBcmXRwRMWPxDNYAODavKV2IlRy5YeiUSzC8l0If3gcKKU+kJyVIeHZVAA+pIhfKZRhHIcIXODo1VXAGNL43xFr1cvTBVtLlWxpugscB3s+MIn1bVNZ1x/brmuS/pI/SQpDsz0SE4KsbhE7jOWTAm7k+92poJyaHRCAmxe7/TDqTg/piS+ilRCdSpkHon0Ju61+ioCdah5qWvQc+QgjYAWdNaKMj7ZAPrInJdljG1Y0UPx9n9gcSwW1s3VL6JJeEu59PMqDku+Le74DZVdpZJ6AMN8kJeuaZR8Fh7e5nQ3B2ovAVhAoQtPOC2Jq1ilj9MvGuoFYIrpPOcIXsWVNr5YAMokLQ97YW8/YRmurI1MC4qM/JFXya6zXtXAsszZXkVQC78Iy90ljwlG2vAkbDL9t/1X8oXRnB5r0CQ2pSJ1plm3nAiHGK+KidnRULypNEnZIEFdrBAVVcGT1NKW95ReItJLOSTpFFFyEI+/GxDOcaVk3XH98TW+/rgmdEF4YbBLm0AHXAbveyOunr8GD0uGEYA94RLGZQqZXsVrIG8mFSN3A5UkIjPyAEouFEBTeNIcB3QHBdjPjGFdhiiTA8W9gqfETDp+M6KJa2XMCDKqsvUWoM6SJAfL98XczsdwhBaNQbHzCPhSZUJsEdaKFIvjvUMJwIcjVlkVMIg0lRS62WV5Be+Fk3PN/S6K3fpmmu4qEuwq+X+gpaqHw0xT9EtxWaSVm7eMDk0TqmfTvWdlTm/pnn7niQVDT62d2Od730LKiT0b557Ic6+RpUBVu7HrSaXr1xaS2XRV0KXn84S3oHqYO5g4Lb6gcKkmpEkdVpl8ATggR2aRTdQT7+3Q==
  template:
    metadata:
      name: ocir-secret
      namespace: resume-app
    type: kubernetes.io/dockerconfigjson
