---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocir-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBYi68wGXQF5KbuLHU+Qg5k+F4ABz6Z+cEg7ATC+KVw1k6CNc/2C6czxWIHeUANWGtvhca1qlEMd7sXCIQcmInaImU4biXOfmdYB/6Dv8Ugd5wDIwElymashUJB0KmTSiyulChGrua0QJtWdJD3Ec7JJbOIV1F1EGHzCF2/8eyVDbLOJ6GAb3v0FB/PFrB2xpzB3EaYzsi2K+b2JQuL4UGZz/PBsfSPl4DIq/ydO54IAv/gFCyHq+R+McbqexPpHm2J2uaXrS08Nt/J+TEaPqzXCScSVDykmuuWzxqhsCHAlLi1ZvwxzaG3fpHl+5fTnTuVGzXNzHREvrhJpvPCXCJq8SGXSujzgK74KINKeXH4uJ2ZrV7k0r339liqW7rap1JQ2+8f0xpGPMQeW5gXIPyK5W7gWWeZR4A+igAz+Z1ZZ4MPQIuPB64MOq9gE+CVYJUm40fOeybFuoWyMlfYdknPxP2if0/sekiYTTRTe8urX9x7/OV9N+erTGBBnir8OwrC428t7k8x82XrVukTv3wmP3ol+3KgG/qdElWQ9kvpC6tw6C6ErcvxvqtJn3iYUsXRZBHKV41XRkMLqjxDZtAbnTGud5CRSdZD+8i8PNmZA3M4u7PlrqtNsFJzl81tUKzxQrDPWkFkH2LXaqyDewcgvzo3VQncIYPrXvrTy24KCpoeMdR1mcPS7wkOtY9sEpZDVTXlfMyA6TpMKyxu8pMI769Ygfv6+3rpC3JrgXoxVjhfaHPWPhySKuH+2nCtwG2dmzBv2hdHi2gxMtPcF4GOHJltMlwT3AIxgUnoB9n/VrooY8LcyBIYv+s7Zc/Cmjv4HbgKi6/bWlTDlrpOW+Zi5pXbmpBC30tpN8DxdOueRZqkj2oKs3W83De4yYqjBPjQH/vutQMlfT9knVpoBDvXHyttbOjoht1EgY1CWyOZMr9MfHJbQSaHVBjiolwZcaKE27zhl6Gk
  template:
    metadata:
      name: ocir-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
