---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocir-secret
  namespace: resume-app
spec:
  encryptedData:
    .dockerconfigjson: AgBFV5vLO2nmSDVdK0oUEo8u87xtQb8qSLNpgpBQaFfFvmTP01mOQxB7ChQKhgP8MuPMTYx0b4Ne8qxY7fbq1mjhpiA/Jrm5q56IEBmwIKkw4PZQluTjceBFM1yLbIyklYBeR9ijyFFY6vLi8zvEFEXSFNrHozEMwDy62DK7cQQTwjMO6ID2WVzvn8mTrqFp/XnsDd/0qCZ75X46tENeftiQ0yAVt6UIeZ6hKG1H9Uz0uhPxV7+7kSf/g5Q7ZzdjUejm+EKkcJApXh3u4nBKicX/H9J1f9lF49WiVSD20/HkA+grHQAn6Ceu4pRUwoFN8a6lHfvDn4XCFY9lIPxVZUXK17Ib8V0pUMarl/PZC8y/F6QnDhDFsQqFsINWvMVC9EmGpHwikhofsh86Wt1uOUrxnwn4NkNCyTftewCO1cZsJzcs7GkYCqtAFzwAldIWa+4/e3avjtv3ByGh63C+p8kk2DHvY9+XkPachizVAxfPS8RYihdAC+KR8CSRVN4TAP1WUFNy3tTV71cTfMSpPZ3LlwiO4aXzb2SzKpfAQqV2jc8BM9YTJ0PNF/emHUhMhx26i0MrvJx7loch1mdETxl/cr4tIrQabJuY5zSc2vUTCgvbDVJGraVHcjX7225W6B1As8k09v/fLHgNHE9Ytbzn5lpFdK8MaLZIrInRc+4gS7SQCIqpnPYyl5adkzP4HxblFU1QaHzvTeghKlvK+Wtm0ZYW5+q/l8RFfiS4X1JH+6+XQbBGtgM7625nilri+CpAWgLexQeIiH7jFgPkWIxLZwj7vIj6/l+vGWWPbTVUoYFqSlHYmUJtaLXwt1iY2anrGIOpuFO5LgSudfOPkywjshqTymj6a6mrrk6dHAJDDEV3hbT2SKW7tFiH+Yc62w8wMAh/kfrL4EshrsdYj0w2vUjIDvxX4w9MeuJjU9I2P9HUn95zS1yNBPrVngReWmS+Ov/7m8s6eYmvjRATl47ttgUsmUktZhxG8V8dtbF5gJdQuWF6G9ZstwYHb/texpO4jImd
  template:
    metadata:
      name: ocir-secret
      namespace: resume-app
    type: kubernetes.io/dockerconfigjson
