apiVersion: batch/v1
kind: Job
metadata:
  name: create-postgres-dir
  namespace: default
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-1
      containers:
        - name: create-dir
          image: busybox
          command:
            [
              "sh",
              "-c",
              "mkdir -p /host-mnt/data/resume-postgres && chmod 777 /host-mnt/data/resume-postgres",
            ]
          volumeMounts:
            - name: host-mnt
              mountPath: /host-mnt
      restartPolicy: Never
      volumes:
        - name: host-mnt
          hostPath:
            path: /mnt
            type: DirectoryOrCreate
