apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-network-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
    targetRevision: main
    path: cluster-resources/networkpolicies
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
