apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: platform
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
    targetRevision: main
    path: cluster-resources/sealed-secrets
    kustomize:
      version: v5.0.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
