apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: platform
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
    targetRevision: main
    path: cluster-resources
    directory:
      recurse: false
      include: '{storage-class-*,pv-*,pvc-*}.yaml'
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
