apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: platform
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 0.5.0
      helm:
        releaseName: alloy
        valueFiles:
          - $values/charts/alloy/values.yaml
    - repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
      targetRevision: main
      path: charts/alloy
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
