---
# ArgoCD Image Updater CRDs - platform-level Application (moved from bootstrap)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
    targetRevision: main
    path: cluster-resources/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
