---
# ArgoCD Application to install the OCI Block Storage CSI driver
# This template references the local `cluster-resources/csi/oci-csi-driver` directory.
# Keep OCI credentials (SealedSecret) in `cluster-resources/sealed-secrets/` when needed.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "99"
spec:
  project: platform
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure
    targetRevision: main
    path: cluster-resources/csi/oci-csi-driver
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: csi-oci-controller
      namespace: kube-system
      jsonPointers:
        - /metadata/generation
        - /metadata/annotations/deployment.kubernetes.io~1revision
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
