apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: platform
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.17.3
      helm:
        releaseName: sealed-secrets
        valueFiles:
          - $values/charts/sealed-secrets/values.yaml
    - repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
      targetRevision: main
      path: charts/sealed-secrets
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
