apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-appset
  namespace: argocd
  annotations:
    # Ensure platform resources, projects and CRDs apply before apps
    argocd.argoproj.io/sync-wave: "21"
spec:
  # NOTE: This is a placeholder/template for future conversion of per-app manifests
  # to descriptor-style files (like observability/grafana-app.yaml). Presently, apps/
  # contains full ArgoCD Application manifests; convert them to descriptors to use
  # this ApplicationSet. The template below is intentionally inert/illustrative.
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        revision: main
        files:
          - path: "argocd-applications/apps/resume-backend-app.yaml"
          - path: "argocd-applications/apps/resume-frontend-app.yaml"
          - path: "argocd-applications/apps/resume-postgres-app.yaml"
          - path: "argocd-applications/apps/frolf-backend-app.yaml"
          - path: "argocd-applications/apps/frolf-discord-app.yaml"
          - path: "argocd-applications/apps/frolf-postgres-app.yaml"
          - path: "argocd-applications/apps/frolf-nats-app.yaml"
  template:
    metadata:
      name: '{{ trimSuffix ".yaml" .path.filename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        targetRevision: main
        # The template uses the path to the application manifest file so the generated
        # Application receives the same source. Template expects the Application file
        # to be a complete ArgoCD Application manifest for the app.
        # .path is an object; use .path.path to reference the file path string.
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
      metadata:
        annotations:
          # ensure generated apps sync later so AppProjects and platform resources exist
          argocd.argoproj.io/sync-wave: "21"
