apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        revision: main
        files:
          - path: "apps/*.yaml" # <-- app descriptors (NO templating!)
  template:
    metadata:
      name: "{{ .path.basename }}"
      labels:
        category: application
        managed-by: lich-king
    spec:
      project: "{{ .spec.project }}"
      source:
        repoURL: "{{ .spec.source.repoURL }}"
        targetRevision: "{{ .spec.source.targetRevision }}"
        path: "{{ .spec.source.path }}"
        kustomize: {} # ArgoCD uses kustomize mode automatically
      destination:
        server: "{{ .spec.destination.server }}"
        namespace: "{{ .spec.destination.namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
