apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        revision: main
        files:
          - path: "argocd-applications/apps/*.yaml"

  template:
    metadata:
      name: "{{ .path.basenameNormalized }}"
      labels:
        category: application
        managed-by: lich-king
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "20" .metadata.annotations.syncWave }}'

    spec:
      project: '{{ default "default" .spec.project }}'

      source:
        repoURL: "{{ .spec.source.repoURL }}"
        targetRevision: "{{ .spec.source.targetRevision }}"
        path: "{{ .spec.source.path }}"
        
        # Always include kustomize section, but it can be empty
        kustomize:
          images:
          {{- if .spec.source.kustomize }}
          {{- if .spec.source.kustomize.images }}
          {{- range .spec.source.kustomize.images }}
          - name: '{{ .name }}'
            {{- if .newName }}
            newName: '{{ .newName }}'
            {{- end }}
            {{- if .newTag }}
            newTag: '{{ .newTag }}'
            {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}

      destination:
        server: "{{ .spec.destination.server }}"
        namespace: "{{ .spec.destination.namespace }}"

      syncPolicy:
        automated:
          prune: {{ if .spec.syncPolicy.automated }}{{ .spec.syncPolicy.automated.prune | default false }}{{ else }}false{{ end }}
          selfHeal: {{ if .spec.syncPolicy.automated }}{{ .spec.syncPolicy.automated.selfHeal | default false }}{{ else }}false{{ end }}
        syncOptions:
          - CreateNamespace=true
