apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"

spec:
  goTemplate: true

  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        revision: main
        files:
          - path: "argocd-applications/apps-descriptors/*.yaml"

  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "21" .syncWave }}'

    spec:
      project: '{{ default "default" .project }}'

      # ---------------------------
      # Sources handling
      # ---------------------------
      # We must use 'sources' (plural) to maintain valid YAML structure.
      # The '{{ if }}' logic cannot be used to switch keys (source vs sources)
      # because it breaks the YAML parser before templating occurs.
      sources:
    {{- toYaml .sources | nindent 8 }}

      destination:
        server: '{{ default "https://kubernetes.default.svc" .destination.server }}'
        namespace: '{{ default "default" .destination.namespace }}'

      # ---------------------------
      # Sync policy
      # ---------------------------
      # Similar to sources, we define the structure explicitly to keep YAML valid.
      # If .syncPolicy is provided in the descriptor, we use its values.
      # Otherwise, we default to the values below.
      syncPolicy:
{{- if .syncPolicy }}
{{ toYaml .syncPolicy | nindent 6 }}
{{- else }}
        automated:
          prune: false
          selfHeal: false
{{- end }}

      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          jsonPointers:
            - /spec/syncPolicy
            - /spec/syncWindows

      preservedFields:
        annotations:
          - argocd.argoproj.io/skip-reconcile
