apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"

spec:
  goTemplate: true

  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        revision: main
        files:
          - path: "argocd-applications/apps-descriptors/*.yaml"

  template:
    metadata:
      name: '{{ .name }}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "21" .syncWave }}'

    spec:
      project: '{{ default "default" .project }}'

      # ---------------------------
      # Sources handling
      # ---------------------------
      # We must explicitly iterate over sources to keep the file valid YAML.
      # We cannot use 'toYaml' for the root list because '{{' confuses the parser.
      sources:
      {{- range $source := .sources }}
        - repoURL: '{{ $source.repoURL }}'
          targetRevision: '{{ $source.targetRevision }}'
          path: '{{ $source.path }}'
          {{- if $source.ref }}
          ref: '{{ $source.ref }}'
          {{- end }}
          {{- if $source.chart }}
          chart: '{{ $source.chart }}'
          {{- end }}
          # If you need Helm/Kustomize params later, they must be added here manually
          # or structured carefully to avoid YAML parsing errors.
      {{- end }}

      destination:
        server: '{{ default "https://kubernetes.default.svc" .destination.server }}'
        namespace: '{{ default "default" .destination.namespace }}'

      # ---------------------------
      # Sync policy
      # ---------------------------
      syncPolicy:
        automated:
          prune: '{{ if .syncPolicy }}{{ .syncPolicy.automated.prune }}{{ else }}false{{ end }}'
          selfHeal: '{{ if .syncPolicy }}{{ .syncPolicy.automated.selfHeal }}{{ else }}false{{ end }}'

      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          jsonPointers:
            - /spec/syncPolicy
            - /spec/syncWindows

      preservedFields:
        annotations:
          - argocd.argoproj.io/skip-reconcile
