apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true

  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        revision: main
        files:
          - path: "argocd-applications/apps/*.yaml"

  template:
    metadata:
      name: "{{ .path.basenameNormalized }}"
      labels:
        category: application
        managed-by: lich-king

    spec:
      project: "{{ default "platform" .spec.project }}"

      source:
        repoURL: "{{ .spec.source.repoURL }}"
        targetRevision: "{{ .spec.source.targetRevision }}"
        path: "{{ .spec.source.path }}"

      destination:
        server: "{{ .spec.destination.server }}"
        namespace: "{{ .spec.destination.namespace }}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
