apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        revision: main
        files:
          - path: "apps/*.yaml"

  template:
    metadata:
      name: "{{ .path.basenameNormalized }}"
      labels:
        category: application
        managed-by: lich-king
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "20" .metadata.annotations.syncWave }}'

    spec:
      # FIX: Add quotes around the entire line
      project: '{{ default "default" .spec.project }}'

      source:
        repoURL: "{{ .spec.source.repoURL }}"
        targetRevision: "{{ .spec.source.targetRevision }}"
        path: "{{ .spec.source.path }}"

        {{- if .spec.source.kustomize }}
        kustomize:
          {{- if .spec.source.kustomize.images }}
          images:
            {{- range .spec.source.kustomize.images }}
            - name: '{{ .name }}'
              newName: '{{ .newName }}'
              newTag: '{{ .newTag }}'
            {{- end }}
          {{- end }}
        {{- end }}

      destination:
        server: "{{ .spec.destination.server }}"
        namespace: "{{ .spec.destination.namespace }}"

      syncPolicy:
        {{- if .spec.syncPolicy }}
        {{- if .spec.syncPolicy.automated }}
        automated:
          # FIX: Use proper boolean syntax (no quotes for true/false)
          prune: {{ .spec.syncPolicy.automated.prune | default false }}
          selfHeal: {{ .spec.syncPolicy.automated.selfHeal | default false }}
        {{- end }}
        {{- end }}
        syncOptions:
          - CreateNamespace=true
