apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"

spec:
  goTemplate: true

  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        revision: main
        files:
          - path: "argocd-applications/apps-descriptors/*.yaml"

  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "21" .syncWave }}'

    spec:
      project: '{{ default "default" .project }}'

      # ---------------------------
      # Sources handling
      # ---------------------------
      # We must use 'sources' (plural) to maintain valid YAML structure.
      sources:
{{ toYaml .sources | nindent 8 }}

      destination:
        server: '{{ default "https://kubernetes.default.svc" .destination.server }}'
        namespace: '{{ default "default" .destination.namespace }}'

      # ---------------------------
      # Sync policy
      # ---------------------------
      # If .syncPolicy is provided in the descriptor, render it; otherwise default.
      syncPolicy:
{{ toYaml .syncPolicy | nindent 8 }}

      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          jsonPointers:
            - /spec/syncPolicy
            - /spec/syncWindows

      preservedFields:
        annotations:
          - argocd.argoproj.io/skip-reconcile
