apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-resources-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: namespaces
            path: cluster-resources/namespaces
            wave: "1"
            prune: "false"
          - name: storage
            path: cluster-resources
            wave: "2"
            prune: "true"
          - name: projects
            path: cluster-resources/projects
            wave: "2"
            prune: "true"
          - name: networkpolicies
            path: cluster-resources/networkpolicies
            wave: "3"
            prune: "true"
  template:
    metadata:
      # Use the element 'name' from the list generator; the previous
      # expression assumed .path was an object with a filename field,
      # which is not true for this list generator (it is a string).
      name: "cluster-{{ .name }}"
      annotations:
        # Default to low-number waves for cluster resources; per-element
        # 'wave' value is applied to each generated app
        argocd.argoproj.io/sync-wave: '{{ default "1" .wave }}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        targetRevision: main
        # The generator provides 'path' as a simple string for each
        # element in this list generator, so reference it directly.
        path: "{{ .path }}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          # For safety, namespaces won't be removed by auto-prune. Other items
          # like storage and network policies are safe to prune and will be
          # opted-in via the element 'prune' flag in the generator when needed.
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          jsonPointers:
            - /spec/syncPolicy
