apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-namespaces
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        revision: main
        files:
          - path: "cluster-resources/namespaces/*.yaml"
  template:
    metadata:
      name: '{{ trimSuffix ".yaml" .path.filename }}-namespace'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: platform
      source:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        targetRevision: main
        path: "{{ .path.path }}"
        directory:
          recurse: false
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
