apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        revision: main
        files:
          - path: "argocd-applications/platform/*.yaml"
  template:
    metadata:
      name: '{{ trimSuffix ".yaml" .path.filename }}'
      annotations:
        argocd.argoproj.io/sync-wave: "5"
    spec:
      project: platform
      source:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      # Avoid AppSet clobbering per-app syncPolicy or 'skip-reconcile' annotation
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          jsonPointers:
            - /spec/syncPolicy
      preservedFields:
        annotations:
          - argocd.argoproj.io/skip-reconcile
