apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        revision: main
        # Only match files that start with a numeric prefix so bulk generators don't pick up
        # manually-managed Application manifests (like sealed-secrets-manifests.yaml).
        files:
          - path: "argocd-applications/platform/[0-9]*.yaml"
          - path: "argocd-applications/platform/sealed-secrets-manifests.yaml"
  template:
    metadata:
      name: '{{ trimSuffix ".yaml" .path.filename }}'
      annotations:
        argocd.argoproj.io/sync-wave: "5"
    spec:
      project: platform
      source:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .spec.destination.namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      # Avoid AppSet clobbering per-app syncPolicy or 'skip-reconcile' annotation
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          jsonPointers:
            - /spec/syncPolicy
