apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: frolf-bot
spec:
  limits:
    - type: Container
      default:
        cpu: 250m
        memory: 256Mi
      defaultRequest:
        cpu: 25m
        memory: 64Mi
