apiVersion: v1
kind: Namespace
metadata:
  name: frolf-bot
  labels:
    name: frolf-bot
    app: frolf-bot
    managed-by: argocd
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn-version: v1.31
    pod-security.kubernetes.io/audit-version: v1.31
