apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frolf-bot.yaml
  - observability.yaml
  - resume-app.yaml
  - resume-db.yaml
  - tailscale.yaml
  - frolf-bot-limits.yaml
  - resume-app-limits.yaml
  - resume-db-limits.yaml
