apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    name: tailscale
    app.kubernetes.io/component: platform
    managed-by: argocd
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn-version: v1.31
    pod-security.kubernetes.io/audit-version: v1.31
