apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frolf-bot
  namespace: argocd
spec:
  description: "Frolf Bot multi-tenant project"

  sourceRepos:
    - "https://github.com/Black-And-White-Club/frolf-bot-infrastructure.git"
    - "https://github.com/Black-And-White-Club/*"

  destinations:
    - namespace: "guild-*"
      server: https://kubernetes.default.svc
    - namespace: "frolf-bot"
      server: https://kubernetes.default.svc
    - namespace: "postgres-frolf"
      server: https://kubernetes.default.svc
    - namespace: "nats-frolf"
      server: https://kubernetes.default.svc
    - namespace: "argocd"
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: ""
      kind: PersistentVolume
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

  namespaceResourceWhitelist:
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: apps
      kind: ReplicaSet
    - group: apps
      kind: StatefulSet
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
