apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: "Platform infrastructure and shared services"

  # Allow your Git repo *and* external Helm repos
  sourceRepos:
    - "https://github.com/Black-And-White-Club/all-infrastructure.git"
    - "https://grafana.github.io/helm-charts"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://argoproj.github.io/argo-helm"
    - "https://kubernetes.github.io/ingress-nginx"
    - "https://nats-io.github.io/k8s/helm/charts/"
    - "https://bitnami-labs.github.io/sealed-secrets"
    - "*" # optional but useful during bootstrap

  # Allow ALL namespaces AND cluster-scoped resources
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
    - namespace: ""
      server: https://kubernetes.default.svc # required for Namespaces, CRDs

  # Allow cluster-scoped resources used by Helm charts and kustomize
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  # Namespace-scoped resources (safe since repos are restricted)
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
