apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - discord-deployment.yaml
labels:
  - includeSelectors: true
    pairs:
      app: frolf-bot-discord
      managed-by: lich-king
  - pairs:
      app.kubernetes.io/name: frolf-bot-discord
      app.kubernetes.io/instance: frolf-bot
      app.kubernetes.io/component: bot
      app.kubernetes.io/part-of: frolf-bot
      app.kubernetes.io/managed-by: argocd
