apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
    targetRevision: main
    path: argocd
    directory:
      recurse: true
      include:
        - platform/*.yaml
        - projects/*.yaml
        - apps/*.yaml
        - observability/*.yaml
        - cluster-resources/*.yaml
      exclude:
        - root-app.yaml
        - "**/kustomization.yaml"
        - "**/kustomization.yml"
        - "**/Kustomization"
        - README.md
        - image-updaters/**

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
