apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-lich-king
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
    targetRevision: main
    path: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
