apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frolf-bot
resources:
  - ../../base
images:
  - name: frolf-bot-ops
    newName: us-ashburn-1.ocir.io/id2uwn5pyixh/frolf-bot/ops
    newTag: v1.0.6
  - name: us-ashburn-1.ocir.io/id2uwn5pyixh/frolf-bot/ops
    newTag: v1.0.6
