apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-local-pv
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
  local:
    path: /mnt/data/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-1 # change to the node hostname where this data directory exists
