apiVersion: v1
kind: PersistentVolume
metadata:
  name: resume-db-local-pv
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgres-resume-backend
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
  local:
    path: /mnt/data/resume-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-1 # change to the actual node name where the data disk is attached (worker-1 by default)
