apiVersion: v1
kind: PersistentVolume
metadata:
  name: resume-postgres-local-pv
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgres-resume-postgres
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
  local:
    path: /mnt/data/resume-postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-1
