apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-local-pvc
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  volumeName: grafana-local-pv
