apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-backend-0
  namespace: resume-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 8Gi
  volumeName: resume-postgres-local-pv
