apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
reclaimPolicy: Retain
# Note: This StorageClass uses static PV provisioning (no-provisioner).
# PVs must be pre-created manually. PVs that use local-storage will be
# node-affinitized and not portable across nodes.
