apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: observability
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.2.0
      helm:
        releaseName: grafana
        valueFiles:
          - $values/charts/grafana/values.yaml
    - repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
      targetRevision: main
      path: charts/grafana
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: grafana
      namespace: observability
      jsonPointers:
        - /data/admin-password
    - group: apps
      kind: Deployment
      name: grafana
      namespace: observability
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
