apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 10.2.0
    helm:
      releaseName: grafana
      values: |
        ## Grafana overlay for local node storage
        ## Use this overlay for clusters that use a node-local storage class (local-storage or local-path)
        ## Update storageClassName to match your local storage provisioner and size to your needs.

        persistence:
          enabled: true
          storageClassName: local-storage
          size: 2Gi
          # Let the chart auto-create the PVC. It will bind to the grafana-pv PersistentVolume
          # that is pre-provisioned in cluster-resources.
          volumeName: grafana-pv

        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          path: /
          pathType: Prefix
          hosts:
            - grafana.jaromero.cloud
          tls:
            - secretName: grafana-tls
              hosts:
                - grafana.jaromero.cloud
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
