apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 10.2.0
    helm:
      releaseName: grafana
      values: |
        ## Grafana overlay for local node storage
        ## Use this overlay for clusters that use a node-local storage class (local-storage or local-path)
        ## Update storageClassName to match your local storage provisioner and size to your needs.

        persistence:
          enabled: true
          storageClassName: local-storage
          size: 2Gi
          # Bind to a pre-provisioned PVC if needed. Provide existingClaim matching a PVC in the observability namespace
          # or provide a volumeName to match a static PersistentVolume. For dynamic provisioning with local-path,
          # omitting these will allow the chart to create the PVC automatically.
          existingClaim: grafana-pvc
          volumeName: grafana-pv
        # Keep datasources and other config as in default values.yaml

        ## NOTE: To use a static PV setup, provide a PVC named `grafana-pvc` in the `observability` namespace
        ## and set persistence.enabled to true and persistence.size to the claim size.
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
