apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: platform
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-state-metrics
      targetRevision: 6.4.1
      helm:
        releaseName: kube-state-metrics
        valueFiles:
          - $values/charts/kube-state-metrics/values.yaml
    - repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
      targetRevision: main
      path: charts/kube-state-metrics
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
