apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frolf-postgres-backup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  revisionHistoryLimit: 3
  project: apps
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
    targetRevision: main
    path: cluster-resources/cronjobs
  destination:
    server: https://kubernetes.default.svc
    namespace: frolf-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
