apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frolf-nats
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: apps
  sources:
    - repoURL: https://nats-io.github.io/k8s/helm/charts/
      chart: nats
      targetRevision: 1.2.5
      helm:
        valueFiles:
          - $values/charts/nats/values.yaml
    - repoURL: https://github.com/Black-And-White-Club/all-infrastructure.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: frolf-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
