---
# The Lich King: Root Application that bootstraps all platform and application resources
# Best Practice: Simple Application (not ApplicationSet) that deploys other ApplicationSets
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-lich-king
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure
    targetRevision: main
    path: argocd-applications
    directory:
      recurse: true
      include: "*-appset.yaml"
    # ensure platform resources are applied before apps
    # (AppSets at root should include infrastructure/appsets and platform/)
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
