---
# The Lich King: Root Application that bootstraps all platform and application resources
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-lich-king
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure
    targetRevision: main
    path: argocd-applications/applicationsets
    # The Lich King should only create ApplicationSets. Pointing at
    # `argocd-applications/applicationsets` prevents duplication where
    # both The Lich King and other static Application manifests manage
    # the same resources.

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
