apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
spec:
  description: "Observability project for Grafana/Loki/Tempo/monitoring stacks"

  sourceRepos:
    - "https://github.com/Black-And-White-Club/all-infrastructure.git"
    - "https://github.com/Black-And-White-Club/*"

  destinations:
    - namespace: "observability"
      server: https://kubernetes.default.svc
    - namespace: "grafana"
      server: https://kubernetes.default.svc
    - namespace: "argocd"
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: monitoring.coreos.com
      kind: Prometheus
