# Base Cluster Resources for platform bootstrap (moved from bootstrap/00-platform-base.yaml)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-cluster-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure
    targetRevision: main
    path: cluster-resources/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # NOTE: hostPath/local PV manifests have been removed; charts create PVCs now via storageClass 'oci-block-storage'.
