apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: resume
  namespace: argocd
spec:
  description: "Resume multi-tenant project for the Resume app"

  sourceRepos:
    - "https://github.com/Black-And-White-Club/resume-infrastructure.git"
    - "https://github.com/Black-And-White-Club/*"

  destinations:
    - namespace: "resume-app"
      server: https://kubernetes.default.svc
    - namespace: "resume-db"
      server: https://kubernetes.default.svc
    - namespace: "argocd"
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: ""
      kind: PersistentVolume
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

  namespaceResourceWhitelist:
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: apps
      kind: ReplicaSet
    - group: apps
      kind: StatefulSet
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
