apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frolf-nats
  namespace: argocd
spec:
  project: frolf-bot
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure
    targetRevision: main
    path: kustomize/frolf-nats
  destination:
    server: https://kubernetes.default.svc
    namespace: frolf-bot
  syncPolicy:
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: frolf-nats
      namespace: argocd
    spec:
      project: frolf-bot
      source:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure
        targetRevision: main
        path: kustomize/frolf-nats
      destination:
        server: https://kubernetes.default.svc
        namespace: frolf-bot
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
