apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frolf-postgres
  namespace: argocd
spec:
  project: frolf-bot
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure
    targetRevision: main
    path: kustomize/frolf-postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-frolf
  syncPolicy:
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: frolf-postgres
      namespace: argocd
    spec:
      project: frolf-bot
      source:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure
        targetRevision: main
        path: kustomize/frolf-postgres
      destination:
        server: https://kubernetes.default.svc
        namespace: postgres-frolf
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
