apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frolf-discord
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  finalizers:
    - resources-finalizer.argocroj.argocroj.io
spec:
  project: frolf-bot
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure
    targetRevision: main
    path: kustomize/frolf-discord
  destination:
    server: https://kubernetes.default.svc
    namespace: frolf-bot
  syncPolicy:
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: frolf-discord
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "21"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: frolf-bot
      source:
        repoURL: https://github.com/Black-And-White-Club/all-infrastructure
        targetRevision: main
        path: kustomize/frolf-discord
      destination:
        server: https://kubernetes.default.svc
        namespace: frolf-bot
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
