apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resume-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: resume
  sources:
    - repoURL: https://github.com/Black-And-White-Club/all-infrastructure
      targetRevision: main
      path: manifests/resume-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: resume-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
