---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imageupdaters.argocd-image-updater.argoproj.io
spec:
  group: argocd-image-updater.argoproj.io
  names:
    kind: ImageUpdater
    listKind: ImageUpdaterList
    plural: imageupdaters
    singular: imageupdater
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                  description: Namespace where ArgoCD applications are located
                applicationRefs:
                  type: array
                  items:
                    type: object
                    properties:
                      namePattern:
                        type: string
                        description: Pattern to match application names
                      images:
                        type: array
                        items:
                          type: object
                          properties:
                            alias:
                              type: string
                              description: Alias for the image
                            imageName:
                              type: string
                              description: Full image name (registry/repo)
                            commonUpdateSettings:
                              type: object
                              properties:
                                updateStrategy:
                                  type: string
                                  description: Update strategy (semver, latest, digest, name)
                                allowTags:
                                  type: string
                                  description: Pattern to filter allowed tags
                                ignoreTags:
                                  type: string
                                  description: Pattern to filter ignored tags
                writeBackConfig:
                  type: object
                  properties:
                    method:
                      type: string
                      description: Write-back method (git, argocd)
                    gitConfig:
                      type: object
                      properties:
                        repository:
                          type: string
                          description: Git repository URL
                        branch:
                          type: string
                          description: Git branch to write to
                        writeBackTarget:
                          type: string
                          description: Path or target for write-back
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
